baseURL = 'https://jbenninghoff.com/'
languageCode = 'en-us'
title = 'John Benninghoff'
theme = 'split'

# Note: the Split theme documentation says to use [[params.visual.image]] (https://github.com/escalate/hugo-split-theme)
# which conflicts with the example at https://github.com/escalate/hugo-split-theme/blob/master/tests/exampleSiteWithImage/hugo.toml
[params.visual.image]
  enable = true
  file = "images/john-benninghoff-full.jpg"

[[params.links]]
  [params.links.list1]
    heading = "Personal"

    [[params.links.list1.link]]
      text = "Information Safety"
      url = "https://information-safety.org"

    [[params.links.list1.link]]
      text = "Transvasive"
      url = "https://transvasive.com"

    [[params.links.list1.link]]
      text = "Bento"
      url = "https://bento.me/jbenninghoff"

[[params.links]]
  [params.links.list2]
    heading = "Social"

    [[params.links.list2.link]]
      text = "LinkedIn"
      url = "https://www.linkedin.com/in/jbenninghoff/"

    [[params.links.list2.link]]
      text = "GitHub"
      url = "https://github.com/jabenninghoff"

    [[params.links.list2.link]]
      text = "Bluesky"
      url = "https://bsky.app/profile/jbenninghoff.com"

[[params.links]]
  [params.links.list3]
    heading = "Professional"

    [[params.links.list3.link]]
      text = "Security Differently"
      url = "https://www.security-differently.com"

    [[params.links.list3.link]]
      text = "ORCID"
      url = "https://orcid.org/0000-0002-6230-4742"

    [[params.links.list3.link]]
      text = "Book a Meeting"
      url = "https://calendly.com/john-security-differently/30min"

# The original template is released under the Creative Commons Attribution 3.0 License.
# Please keep the original attribution link when using for your own project.
# If you'd like to use the template without the attribution, you can check out
# the license option via the template author's website: https://onepagelove.com/split
